[2025-01-25T22:53:21.477+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-25T22:53:21.501+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_1 scheduled__2025-01-25T22:45:00+00:00 [queued]>
[2025-01-25T22:53:21.513+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_1 scheduled__2025-01-25T22:45:00+00:00 [queued]>
[2025-01-25T22:53:21.513+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-25T22:53:21.646+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_and_load_to_mongodb_station_1> on 2025-01-25 22:45:00+00:00
[2025-01-25T22:53:21.659+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extraction_by_hour_dag_v11', 'extract_and_load_to_mongodb_station_1', 'scheduled__2025-01-25T22:45:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/extract_data_by_hour.py', '--cfg-path', '/tmp/tmpmv7gxcfz']
[2025-01-25T22:53:21.663+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask extract_and_load_to_mongodb_station_1
[2025-01-25T22:53:21.667+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=196) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-25T22:53:21.667+0000] {standard_task_runner.py:72} INFO - Started process 204 to run task
[2025-01-25T22:53:21.760+0000] {task_command.py:467} INFO - Running <TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_1 scheduled__2025-01-25T22:45:00+00:00 [running]> on host 55ca55e0aadf
[2025-01-25T22:53:21.930+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extraction_by_hour_dag_v11' AIRFLOW_CTX_TASK_ID='extract_and_load_to_mongodb_station_1' AIRFLOW_CTX_EXECUTION_DATE='2025-01-25T22:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-25T22:45:00+00:00'
[2025-01-25T22:53:21.931+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-25T22:54:07.581+0000] {logging_mixin.py:190} INFO - Erreur lors de l'insertion dans MongoDB : mongodb:27017: [Errno -3] Temporary failure in name resolution (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 67956b72c7fa16499ed4da6a, topology_type: Unknown, servers: [<ServerDescription ('mongodb', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongodb:27017: [Errno -3] Temporary failure in name resolution (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>
[2025-01-25T22:54:07.587+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-25T22:54:07.599+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-25T22:54:07.600+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extraction_by_hour_dag_v11, task_id=extract_and_load_to_mongodb_station_1, run_id=scheduled__2025-01-25T22:45:00+00:00, execution_date=20250125T224500, start_date=20250125T225321, end_date=20250125T225407
[2025-01-25T22:54:07.629+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-25T22:54:07.646+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T22:54:07.650+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
